spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"   # Imports configuration properties from an external Config Server located at the specified URL(https://github.com/alifurkanergvn/bank-config-server/blob/main/gatewayserver.yml). The "optional:" prefix indicates that the application can still start even if the Config Server is unavailable.
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true # Enables the DiscoveryClient integration, allowing the gateway to route requests to services registered with a service discovery server (like Eureka) using their service IDs.
              lower-case-service-id: true # Converts service IDs to lowercase when routing requests. http://localhost:8072/ACCOUNTS/api/create (routes comes from eureka in there all of them uppercase)-> with this conf you can access http://localhost:8072/accounts/api/create

management: # Spring Boot Actuator management endpoints configuration
  endpoints: # Configuration for Actuator's web endpoints
    web: # Web-specific endpoint settings
      exposure: # Defines which endpoints are exposed over the web
        include: "*" # Exposes all available Actuator endpoints (e.g., /actuator/health, /actuator/info, /actuator/metrics, etc.)
        # Be cautious with this setting in production as it can expose sensitive information.
  endpoint:
    gateway:
      access: unrestricted  # Enables unrestricted access to the '/actuator/gateway' endpoint, allowing users to view and manage gateway routes and filters without authentication.
  info: # Configuration for the 'info' endpoint
    env: # Environment information
      enabled: true # Enables the display of environment-specific properties (e.g., properties from application.properties/yaml, system properties, environment variables)
      # within the '/actuator/info' endpoint.
#the application ensures that all management endpoints are accessible, which can be particularly useful during development and debugging
#http://localhost:8080/actuator/refresh (POST request)   Refresh configurations at runtime using /refresh path

# Because of spring-boot-starter-actuator dependency, we can refresh the application settings at runtime but
# we have to use the POST request for all microservices one by one thanks to spring-cloud-starter-bus-amqp dependency
# http://localhost:8080/actuator/busrefresh (POST request) we are just one time refreshing all microservices instances
# and config service will load the latest config data without restart via massage broker(rabbitmq) trigger change event action

# Config Server -> Eureka Server -> accounts, loans, cards -> Gateway Server
# You should follow this order because eureka server send all registered microservices info to gateway server for routing if you up one of microservices after gateway server you cant reach that microservice via gateway server
# http://localhost:8072/actuator -> http://localhost:8072/actuator/gateway/routes  you can see all registered microservices routes info (8072=gateway server port on config server git repo)
# http://localhost:8072/accounts/api/create  you can reach accounts microservice via gateway server (8072=gateway server port on config server git repo)

info:
  app:
    name: "gatewayserver"
    description: "MyBank Gateway Server Application"  # http://localhost:8070/  you can see this info spring eureka page on status link
    version: "1.0.0"

logging:
    level:
        com:
          afe:
            gatewayserver: DEBUG


resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10                     # Number of calls used to calculate the failure rate
      permittedNumberOfCallsInHalfOpenState: 2  # Number of test calls allowed in half-open state
      failureRateThreshold: 50                  # Failure rate percentage threshold to open the circuit
      waitDurationInOpenState: 10000            # Time in milliseconds to wait before transitioning from open to half-open state
#First we call one sample request on postman for seeing circuitbreakers status--> http://localhost:8072/mybank/accounts/api/contact-info
#http://localhost:8072/actuator --> finding in page "circuit" links --> http://localhost:8072/actuator/circuitbreakers  --> you can see circuit breaker status(OPEN/CLOSED/HALF OPEN) for all microservices via gateway server
#http://localhost:8072/actuator/circuitbreakers/{circuitBreakerName}  --> you can see specific microservice circuit breaker details via gateway server --> example: http://localhost:8072/actuator/circuitbreakerevents?name=accountsCircuitBreaker
