server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: "accounts"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true    # Enables OpenFeign circuit breaker for fault tolerance in service-to-service calls
#we pull rabbitmq image from dockerhub with $ docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.12-management
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management: # Spring Boot Actuator management endpoints configuration
  endpoints: # Configuration for Actuator's web endpoints
    web: # Web-specific endpoint settings
      exposure: # Defines which endpoints are exposed over the web
        include: "*" # Exposes all available Actuator endpoints (e.g., /actuator/health, /actuator/info, /actuator/metrics, etc.)
                     # Be cautious with this setting in production as it can expose sensitive information.
  health:
    readiness-state:
      enabled: true   # Enables the readiness state indicator, which shows if the application is ready to serve requests. http://localhost:8071/actuator/health/readiness
    liveness-state:
      enabled: true   # Enables the liveness state indicator, which shows if the application is alive and functioning properly. http://localhost:8071/actuator/health/liveness
  endpoint: # Specific endpoint configurations
    shutdown: # Configuration for the 'shutdown' endpoint
      access: unrestricted # Enables the '/actuator/shutdown' endpoint, allowing the application to be gracefully shut down via an HTTP POST request.
                    # This endpoint is disabled by default for security reasons.
    health:
      probes:
        enabled: true   # Enables health probes, allowing external systems (e.g., Kubernetes) to check the application's health status. http://localhost:8071/actuator/health/
  info: # Configuration for the 'info' endpoint
    env: # Environment information
      enabled: true # Enables the display of environment-specific properties (e.g., properties from application.properties/yaml, system properties, environment variables)
                    # within the '/actuator/info' endpoint.
#the application ensures that all management endpoints are accessible, which can be particularly useful during development and debugging
#http://localhost:8080/actuator/refresh (POST request)   Refresh configurations at runtime using /refresh path

# Because of spring-boot-starter-actuator dependency, we can refresh the application settings at runtime but
# we have to use the POST request for all microservices one by one thanks to spring-cloud-starter-bus-amqp dependency
# http://localhost:8080/actuator/busrefresh (POST request) we are just one time refreshing all microservices instances
# and config service will load the latest config data without restart via massage broker(rabbitmq) trigger change event action


eureka:         # Eureka client and server configurations
  instance:     # Configuration specific to this application's Eureka instance
    preferIpAddress: true     # Indicates that this instance should register its IP address rather than its hostname with Eureka.
                              # When other services discover this instance, they will receive its IP address instead of its hostname.
  client:   # Configuration for the Eureka client (this application)
    fetchRegistry: true         # Indicates whether this client should fetch the registry information from the Eureka server.
                                # 'false' is typically used for a Eureka server itself, or a standalone application that doesn't need to discover other services.
                                # in our individual microservices like accounts, loans and cards this value should be true
    registerWithEureka: true    # Indicates whether this client should register itself with the Eureka server.
                                # 'true' means this application is a microservice and wants to be discovered by other services.
    serviceUrl:     # A map of Eureka server URLs to connect to
      defaultZone: http://localhost:8070/eureka/      # The URL of the Eureka server to which this client will connect.

info:
  app:
    name: "accounts"
    description: "MyBank Accounts Application"  # http://localhost:8070/  you can see this info spring eureka page on status link
    version: "1.0.0"

logging:
  level:
    com:
      afe:
        accounts: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10                     # Number of calls used to calculate the failure rate
      permittedNumberOfCallsInHalfOpenState: 2  # Number of test calls allowed in half-open state
      failureRateThreshold: 50                  # Failure rate percentage threshold to open the circuit
      waitDurationInOpenState: 10000            # Time in milliseconds to wait before transitioning from open to half-open state
#First we call one sample post request on postman for seeing circuitbreakers status--> http://localhost:8072/mybank/accounts/api/create, http://localhost:8072/mybank/cards/api/create?mobileNumber=5391234567, http://localhost:8072/mybank/loans/api/create?mobileNumber=5391234567
#Then calling feign client api with this request http://localhost:8072/mybank/accounts/api/fetchCustomerDetails?mobileNumber=5391234567
#http://localhost:8080/actuator --> finding in page "circuit" links --> http://localhost:8080/actuator/circuitbreakers  --> you can see circuit breaker status(OPEN/CLOSED/HALF OPEN) for all microservices via gateway server
#http://localhost:8080/actuator/circuitbreakerevents --> you can see circuit breaker events details for all microservices via gateway server

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 500
      enableExponentialBackoff: true              # Enables exponential backoff for retry attempts, increasing the wait time after each failure.
      exponentialBackoffMultiplier: 2             # Sets the multiplier for exponential backoff, doubling the wait time after each retry.
      ignoreExceptions:                           # Specifies exceptions that should not trigger a retry, e.g., NullPointerException. Whenever you have retryExceptions this ignoreExceptions unnecessary
        - java.lang.NullPointerException
      retryExceptions:                            # Specifies exceptions that should trigger a retry, e.g., TimeoutException.
        - java.util.concurrent.TimeoutException

resilience4j.ratelimiter:
  configs:
    default:                     # Defines the default configuration for the rate limiter, which can be applied to any rate limiter instance that does not have a specific configuration defined.
      timeoutDuration: 1000      # Sets the maximum time to wait for a permission to execute a request when the rate limit has been exceeded. In this case, it will wait for up to 1000 milliseconds (1 second) before timing out.
      limitRefreshPeriod: 5000   # Sets the period after which the rate limiter's counters are reset, allowing new requests to be processed. In this case, the counters will reset every 5000 milliseconds (5 seconds).
      limitForPeriod: 1          # Sets the maximum number of requests allowed within the defined refresh period. In this case, only 1 request will be allowed every 5 seconds. If more than 1 request is made within that period, subsequent requests will be rate-limited until the counters reset.







#  config:
#    import:
#      - "application_qa.yml"
#      - "application_prod.yml"

#  profiles:
#    active:
#      - "qa"
#
#build:
#  version: "3.0"
#
#accounts:
#  message: "Welcome to MyBank accounts related local APIs "
#  contactDetails:
#    name: "Ali Furkan Erguven - Developer"
#    email: "alifurkanerguven@mybank.com"
#  onCallSupport:
#    - (555) 555-1234
#    - (555) 523-1345
## now we use all config and profile settings on configserver
