spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    #we use active: native for classpath location and file system location
    active: git
  cloud:
    config:
      server:
        #native:
#          search-locations: "classpath:/config"
          #search-locations: "file:///D://Ali Furkan//Projects//MasterMicroservices//Documents//config"
        git:
          uri: "https://github.com/alifurkanergvn/bank-config-server.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  #we pull rabbitmq image from dockerhub with $ docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.12-management
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
    # Refresh configurations at runtime using Spring Cloud Bus & Spring Cloud Config Monitor therefore we dont need
    #any request localhost:8090/actuator/busrefresh
    #Now we created a webhook to listen to the changes on github. Webhook listen to the changes on the main branch if changes are made
    #send request this path http://localhost:8071/monitor with this terminal command: hookdeck listen 8071 source --cli-path /monitor
    #check detail on https://github.com/alifurkanergvn/bank-config-server

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true   # Enables the readiness state indicator, which shows if the application is ready to serve requests. http://localhost:8071/actuator/health/readiness
    liveness-state:
      enabled: true   # Enables the liveness state indicator, which shows if the application is alive and functioning properly. http://localhost:8071/actuator/health/liveness
  endpoint:
    health:
      probes:
        enabled: true   # Enables health probes, allowing external systems (e.g., Kubernetes) to check the application's health status. http://localhost:8071/actuator/health/

encrypt:
  key: "45D81EC1EF61DF9AD8D315BB697F9"

server:
  port: 8071

# we added new eurekaserver.yml on bank-config-server project to use eureka client http://localhost:8071/eurekaserver/default
#Build and run the Eureka Server: Build your EurekaserverApplication project  and run it as a Spring Boot application. Open a web browser and navigate to
#http://localhost:8070. You should see the Eureka Server dashboard, which displays information about registered service instances.
