spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    #we use active: native for classpath location and file system location
    active: git
  cloud:
    config:
      server:
        #native:
#          search-locations: "classpath:/config"
          #search-locations: "file:///D://Ali Furkan//Projects//MasterMicroservices//Documents//config"
        git:
          uri: "https://github.com/alifurkanergvn/bank-config-server.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "45D81EC1EF61DF9AD8D315BB697F9"

server:
  port: 8071
